basePath: /api/v1
definitions:
  v1.ResponseError:
    properties:
      msg:
        example: Error
        type: string
      status:
        example: 500
        type: integer
    type: object
  v1.ResponseUser:
    properties:
      msg:
        example: OK
        type: string
      status:
        example: 200
        type: integer
    type: object
  v1.UserInfo:
    properties:
      password:
        description: 密码
        example: "1233456"
        type: string
      role:
        description: 权限码
        example: 2
        type: integer
      username:
        description: 用户名
        example: lin
        type: string
    type: object
host: localhost:2333
info:
  contact:
    email: 942801422@qq.com
    name: API Support
    url: http://www.swagger.io/support
  description: Gin博客接口文档
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Gin Blog API v1
  version: "1.0"
paths:
  /article/info/{id}:
    get:
      description: 查询单个文章接口
      parameters:
      - default: 1
        description: 文章编号
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: 查询文章成功
          schema:
            $ref: '#/definitions/v1.ResponseUser'
        "400":
          description: 查询文章失败
          schema:
            $ref: '#/definitions/v1.ResponseError'
      summary: 查询单个文章
      tags:
      - 文章接口
  /user/add:
    post:
      description: 新增用户接口
      parameters:
      - description: 用户信息
        in: body
        name: userinfo
        required: true
        schema:
          $ref: '#/definitions/v1.UserInfo'
      responses:
        "200":
          description: 新增用户成功
          schema:
            $ref: '#/definitions/v1.ResponseUser'
        "400":
          description: 新增用户失败
          schema:
            $ref: '#/definitions/v1.ResponseError'
      summary: 新增用户
      tags:
      - 用户接口
swagger: "2.0"
